version: "3"

vars:
  GLOBAL: "GLOBAL"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none

  build:
    desc: Build go program
    cmds:
      - go build -o main

  run:
    desc: Run go program
    cmds:
      - go run ./... -taskfile="{{.TASKFILE}}"
    vars:
      TASKFILE: "{{.TASKFILE}}"

  run:test:
    desc: Run go program for debug
    cmds:
      - task: run
        vars:
          TASKFILE: "Taskfile.test.yml"

  fmt:
    desc: Format go program
    cmds:
      - go fmt ./...

  vet:
    desc: Doctor go program
    cmds:
      - go vet ./...

  test:
    desc: Test all case
    cmds:
      - go test -v ./...

  test:run:
    desc: Test specific case
    cmds:
      - go test -v -run "{{.NAME}}" ./...
    requires:
      vars: [ NAME ]
