version: "3"

vars:
  GLOBAL: "GLOBAL"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none

  build:
    desc: Build go program
    cmds:
      - go build -o main ./cmd

  run:
    desc: Run go program
    cmds:
      - go run ./cmd -taskfile={{.TF}}
    vars:
      TF: '{{.TF}}'

  run:vars:
    desc: Run vars test program
    cmds:
      - go run ./cmd -taskfile=test/Taskfile.vars.yml

  run:includes:
    desc: Run vars test program
    cmds:
      - go run ./cmd -taskfile=test/Taskfile.includes.yml

  fmt:
    desc: Format go program
    cmds:
      - go fmt ./...

  vet:
    desc: Doctor go program
    cmds:
      - go vet ./...

  test:
    desc: Test all case
    cmds:
      - go test -v ./...

  test:run:
    desc: Test specific case
    cmds:
      - go test -v -run "{{.NAME}}" ./...
    requires:
      vars: [ NAME ]
